GET localhost:8080/
Content-Type: application/json

###
GET localhost:8766/gallery/stream/buckets/default
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwiaWF0IjoxNjE5ODkwOTAxLCJleHAiOjE2MTk5NzczMDF9.3-GbPIY2DKdM2lhKF35ZIjLg9c5kRzpJmv_d1spydo5kBz-AfLVHp_dw-znXkn0PYYSTQ_YlpZYy9M0v-_Payw