spring:
  application:
    name: user-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
logging:
  file:
    name: D:\projects\sprint_cloud_netflix\logs\application.log