spring:
  application:
    name: zuul-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

server:
  port: 8766

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true